server:
  host: "0.0.0.0"
  port: 8000
  mode: "debug"
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s
  max_header_bytes: 1048576

services:
  market_data:
    url: "http://localhost:8080"
    timeout: 5s
    max_retries: 3
  order_execution:
    url: "http://localhost:8081"
    timeout: 10s
    max_retries: 2
  strategy_engine:
    url: "http://localhost:8082"
    timeout: 5s
    max_retries: 2
  account_monitor:
    url: "http://localhost:8084"
    timeout: 5s
    max_retries: 3
  dashboard_server:
    url: "http://localhost:8086"
    timeout: 5s
    max_retries: 3
  risk_manager:
    url: "http://localhost:9095"
    timeout: 5s
    max_retries: 2
  configuration:
    url: "http://localhost:8085"
    timeout: 5s
    max_retries: 3

auth:
  enabled: true
  jwt_secret: "test-secret-key-change-in-production-12345"
  jwt_expiry: 24h
  refresh_token_expiry: 168h
  api_keys:
    - key: "test-admin-key-123"
      role: "admin"
    - key: "test-operator-key-456"
      role: "operator"
    - key: "test-viewer-key-789"
      role: "viewer"

rate_limit:
  enabled: true
  global:
    requests_per_second: 100
    burst: 200
  endpoints:
    "/api/v1/orders":
      requests_per_second: 10
      burst: 20
  per_ip:
    requests_per_minute: 300
    burst: 500

cors:
  enabled: true
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization"
    - "X-Request-ID"
    - "X-API-Key"
  exposed_headers:
    - "X-Request-ID"
    - "X-RateLimit-Limit"
    - "X-RateLimit-Burst"
  allow_credentials: true
  max_age: 3600

circuit_breaker:
  enabled: true
  max_requests: 3
  interval: 10s
  timeout: 60s

cache:
  enabled: false

validation:
  enabled: true
  max_request_size: 10485760

load_balancing:
  enabled: false

logging:
  level: "debug"
  format: "console"
  output: "stdout"

metrics:
  enabled: true
  path: "/metrics"

health:
  enabled: true
  path: "/health"
  check_services: false

versioning:
  enabled: true

tls:
  enabled: false

transformation:
  enabled: false

websocket:
  enabled: true
  max_connections: 1000
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s
  ping_interval: 30s
  pong_timeout: 60s

retry:
  enabled: true
  max_attempts: 3
  backoff_multiplier: 2
  initial_interval: 100ms
  max_interval: 5s
  retryable_status_codes:
    - 502
    - 503
    - 504

timeout:
  request_timeout: 30s
  dial_timeout: 10s
  keep_alive: 90s

features:
  enable_tracing: false
  enable_compression: true
  enable_request_id: true
  enable_access_log: true
  enable_error_details: true
