server:
  host: "0.0.0.0"
  port: 9092
  mode: "production"
  readTimeout: 10s
  writeTimeout: 10s
  idleTimeout: 60s
  maxHeaderBytes: 1048576

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  poolSize: 20
  minIdleConns: 10
  marketDataChannels:
    - "market:btcusdt"
    - "market:ethusdt"
    - "market:solusdt"

nats:
  url: "nats://localhost:4222"
  maxReconnects: 10
  reconnectWait: 2
  fillSubject: "trading.fills"
  positionSubject: "trading.positions"

grpc:
  orderExecutionAddr: "localhost:50051"
  timeout: 5s
  maxRetries: 3

engine:
  mode: "simulation"  # live, simulation, observation
  signalBufferSize: 1000
  maxConcurrent: 10
  processingTimeout: 500us
  pluginsDir: "./plugins"
  hotReload: true
  reloadInterval: 30s

strategies:
  enabled:
    - momentum
    - market_making
    - scalping
  configs:
    momentum:
      lookback_period: 20
      threshold: 0.02  # 2% momentum threshold
      max_position: 1000.0
    market_making:
      spread: 0.001  # 10 bps
      order_size: 100.0
      max_inventory: 1000.0
      inventory_skew: 0.5
      min_spread_bps: 5.0
    scalping:
      target_spread_bps: 5.0
      profit_target: 0.001  # 10 bps
      stop_loss: 0.0005  # 5 bps
      max_hold_time_seconds: 60
      max_position: 500.0
  pythonPath: "/usr/bin/python3"
  pythonVenv: ""

risk:
  enabled: true
  maxPositionSize: 1000.0
  maxOrderValue: 50000.0
  maxDailyLoss: 5000.0
  maxDrawdown: 0.10  # 10%
  minAccountBalance: 10000.0
  allowedSymbols:
    - "BTCUSDT"
    - "ETHUSDT"
    - "SOLUSDT"
  blockedSymbols: []
  maxOrdersPerSecond: 10
  maxOrdersPerMinute: 100

logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, console
  output: "stdout"  # stdout, stderr, file
  file: "/var/log/strategy-engine.log"
  maxSize: 100  # MB
  maxBackups: 10
  maxAge: 30  # days
  compress: true

metrics:
  enabled: true
  port: 9092
  path: "/metrics"
  namespace: "strategy_engine"
