# Prometheus configuration for Analytics Service

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'analytics-cluster'
    replica: 'prometheus-1'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files
rule_files: []

# Scrape configurations
scrape_configs:
  # Analytics Service
  - job_name: 'analytics'
    static_configs:
      - targets: ['analytics:9098']
        labels:
          service: 'analytics'
          environment: 'development'

  # PostgreSQL Exporter (if deployed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          database: 'analytics'

  # Redis Exporter (if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
