server:
  http_port: 9097
  websocket_path: /ws
  read_timeout: 10
  write_timeout: 10
  max_connections: 10000

database:
  host: localhost
  port: 5432
  name: messaging
  user: postgres
  password: postgres
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

nats:
  url: nats://localhost:4222

storage:
  type: local  # or s3
  path: ./uploads
  max_file_size: 10485760  # 10MB
  s3_bucket: ""
  s3_region: ""

auth:
  jwt_secret: your-secret-key-change-in-production
  token_expiry: 24h

logging:
  level: info  # debug, info, warn, error
  format: json  # json, pretty
