version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: configuration-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: configuration_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:latest
    container_name: configuration-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--http_port 8222"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  configuration-service:
    build: .
    container_name: configuration-service
    ports:
      - "9096:9096"
      - "9097:9097"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_HTTP_PORT=9096
      - SERVER_GRPC_PORT=9097
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DBNAME=configuration_db
      - DATABASE_SSLMODE=disable
      - NATS_URL=nats://nats:4222
      - LOG_LEVEL=info
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
